version: "3.9"
services:
  spring-api-image:
    image: imagen-tipocambio
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - spring-network

networks:
  spring-network:
volumes:
  mysql-volume: